name: Terraform Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Initialize and Validate Modules
        run: |
          cd modules/vnet
          terraform init -backend=false
          terraform validate

      - name: TFLint
        uses: terraform-linters/tflint-action@v3
        with:
          config_file: .tflint.hcl
          args: --recursive --format=compact